[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "python312Packages.wheel",
  "python312Packages.uvicorn",
  "python312Packages.fastapi",
  "python312Packages.python-dotenv",
  "postgresql"  # dependency psycopg2-binary
]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"
