[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "python312Packages.wheel",
  "python312Packages.virtualenv",
  "postgresql"
]

[phases.build]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = ". venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port 8000"
